import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{padding: '1rem', borderBottom: '1px solid #eee'}}>
            
          <nav>
            <Link href="/">Inicio </Link>
            <Link href="/acerca">Acerca de</Link>
          </nav>
        </header>

        <main style={{padding: '1rem'}}>
          {children}
        </main>
      </body>
    </html>
  );
}
